services:
  # Qdrant vector database service
  qdrant:
    image: qdrant/qdrant:${QDRANT_TAG}
    container_name: qdrant
    environment:
      - QDRANT__SERVICE__GRPC_PORT=6334
      # - QDRANT__SERVICE__API_KEY=${QDRANT__SERVICE__API_KEY}
      - QDRANT__SERVICE__ENABLE_STATIC_CONTENT=true # Web UI
    ports:
      - 6333:6333 # tcp
      - 6334:6334 # grpc
    volumes:
      - ${DATA_PATH}/qdrant/storage:/qdrant/storage
    restart: ${RESTART_POLICY}